In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('/Users/sepilovstepansergeevic/Desktop/Code/neftecode/hack/data/daimler_mixtures_train.csv')
data

,scenario_id,Компонент,Наименование партии,"Массовая доля, %","Температура испытания | ASTM D445 Daimler Oxidation Test (DOT), °C","Время испытания | - Daimler Oxidation Test (DOT), ч","Delta Kin. Viscosity KV100 - relative | - Daimler Oxidation Test (DOT), %","Oxidation EOT | DIN 51453 Daimler Oxidation Test (DOT), A/cm","Количество биотоплива | - Daimler Oxidation Test (DOT), % масс","Дозировка катализатора, категория"
0,train_1,Антиоксидант_5,32,70.832,160,168,25.4,98.04,0,1
1,train_1,Антиоксидант_6,13799.21,70.832,160,168,25.4,98.04,0,1
2,train_1,Антипенная_присадка_3,б/н,3.991,160,168,25.4,98.04,0,1
3,train_1,Базовое_масло_10,0285.21,60.034,160,168,25.4,98.04,0,1
4,train_1,Базовое_масло_17,без номера,84.281,160,168,25.4,98.04,0,1
...,...,...,...,...,...,...,...,...,...,...
2225,train_167,Базовое_масло_1,01595.25,43.229,160,168,-37.0,41.93,0,1
2226,train_167,Базовое_масло_5,01624.25,22.895,160,168,-37.0,41.93,0,1
2227,train_167,Детергент_1,01558.25,8.080,160,168,-37.0,41.93,0,1
2228,train_167,Загуститель_1,01609.25,2.675,160,168,-37.0,41.93,0,1
2229,train_167,Противоизносная_присадка_7,НовочебоксарскХП,31.092,160,168,-37.0,41.93,0,1

In [4]:
properties = pd.read_csv('/Users/sepilovstepansergeevic/Desktop/Code/neftecode/hack/data/daimler_component_properties.csv')
properties

,Компонент,Наименование партии,Наименование показателя,Единица измерения_по_партиям,Значение показателя
0,Детергент_4,0338.22,"Кинематическая вязкость, при 100°C, ASTM D445",мм²/с,16.68
1,Детергент_4,0338.22,"Массовая доля кальция, ASTM D6481",% масс,6.144
2,Детергент_4,0338.22,"Массовая доля цинка, ASTM D6481",% масс,0.0064
3,Детергент_4,0338.22,"Щелочное число, ASTM D2896",мг KOH/г,168
4,Противоизносная_присадка_8,0186.22,"Кинематическая вязкость, при 100°C, ASTM D445",мм²/с,13.74
...,...,...,...,...,...
2636,Базовое_масло_8,typical,"Содержание серы, мг/кг",NaN,<10
2637,Базовое_масло_4,typical,"Содержание серы, мг/кг",NaN,<10
2638,Базовое_масло_16,typical,Содержание ароматики,NaN,<3
2639,Базовое_масло_14,typical,Содержание ароматики,NaN,<3
2640,Базовое_масло_17,typical,Анилиновая точка,NaN,68.4